name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15.0]

    steps:
      - name: Get latest code
        uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install
      - run: yarn build

      # - name: FTP Deploy
      #   uses: SamKirkland/FTP-Deploy-Action@4.0.0
      #   with:
      #     server: ${{ secrets.SERVER_IP }}
      #     username: ${{ secrets.FTP_USER }}
      #     password: ${{ secrets.FTP_PWD }}
      #     local-dir: ./build/
      #     server-dir: ./www/front/blog
      - name: SSH Deploy
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ARGS: '-avzr --delete'
          SOURCE: 'build'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: 'ubuntu'
          TARGET: '/www/front/blog'